[Settings]
ID = "a7d6ffab-f85d-4cc4-b398-daf3f2f9756c"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "react-sorting-hat/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "react-sorting-hat/build/"
  # This will be your default build command
  command = "yarn build"